// parakeet_sp_parity.cpp - SentencePiece encoder parity on real vocabularies.
//
// Loads only the tokenizer KVs of each GGUF (no weights) and checks that
// Tokenizer::encode() reproduces the reference tokenizer's ids for the
// fixture texts in fixtures/parakeet_sp_parity.inc (generated by
// scripts/sp-tokenizer-parity-fixture.py):
//
//   TRANSCRIBE_PARAKEET_GGUF          parakeet-tdt-0.6b-v3 (BPE; HF tokenizer.json)
//   TRANSCRIBE_PARAKEET_UNIFIED_GGUF  parakeet-unified-en-0.6b (BPE; shares the
//                                     nemotron-speech-streaming-en tokenizer)
//   TRANSCRIBE_NEMOTRON35_GGUF        nemotron-3.5-asr-streaming-0.6b (unigram
//                                     labelled "bpe" by older converters)
//
// A variable that is unset, or points at a GGUF with a different vocab
// size, skips that set; all skipped -> exit 77.

#include "gguf.h"
#include "transcribe-tokenizer.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

namespace {

struct Fixture {
    const char *  text;
    const int32_t ids[32];
    size_t        n_ids;
};

#include "fixtures/parakeet_sp_parity.inc"

int g_failures = 0;

// Returns false when the set was skipped.
template <size_t N> bool check_set(const char * env_var, int vocab_size, const Fixture (&fixtures)[N]) {
    const char * path = std::getenv(env_var);
    if (path == nullptr || path[0] == '\0') {
        std::fprintf(stderr, "parakeet_sp_parity: %s not set; skipping\n", env_var);
        return false;
    }
    gguf_init_params gp{};
    gp.no_alloc         = true;
    gp.ctx              = nullptr;
    gguf_context * gguf = gguf_init_from_file(path, gp);
    if (gguf == nullptr) {
        std::fprintf(stderr, "FAIL %s: cannot read %s\n", env_var, path);
        ++g_failures;
        return true;
    }
    transcribe::Tokenizer   tok;
    const transcribe_status st = tok.load(gguf);
    gguf_free(gguf);
    if (st != TRANSCRIBE_OK || tok.n_tokens() != vocab_size) {
        std::fprintf(stderr, "parakeet_sp_parity: %s is not the expected vocab (%d tokens); skipping\n", env_var,
                     tok.n_tokens());
        return false;
    }
    for (const Fixture & f : fixtures) {
        std::vector<int32_t> got;
        const bool           ok = tok.encode(f.text, got) == TRANSCRIBE_OK && got.size() == f.n_ids &&
                                  std::memcmp(got.data(), f.ids, f.n_ids * sizeof(int32_t)) == 0;
        if (!ok) {
            ++g_failures;
            std::fprintf(stderr, "FAIL %s \"%s\"\n  expected:", env_var, f.text);
            for (size_t i = 0; i < f.n_ids; ++i) {
                std::fprintf(stderr, " %d", static_cast<int>(f.ids[i]));
            }
            std::fprintf(stderr, "\n  actual:  ");
            for (const int32_t id : got) {
                std::fprintf(stderr, " %d", static_cast<int>(id));
            }
            std::fprintf(stderr, "\n");
        }
    }
    std::fprintf(stderr, "parakeet_sp_parity: %s: %zu texts checked\n", env_var, N);
    return true;
}

}  // namespace

int main() {
    int ran = 0;
    ran += check_set("TRANSCRIBE_PARAKEET_GGUF", 8193, k_parakeet_v3_fixtures) ? 1 : 0;
    ran += check_set("TRANSCRIBE_PARAKEET_UNIFIED_GGUF", 1025, k_nemotron_en_fixtures) ? 1 : 0;
    ran += check_set("TRANSCRIBE_NEMOTRON35_GGUF", 13088, k_nemotron35_fixtures) ? 1 : 0;
    if (ran == 0) {
        return 77;
    }
    if (g_failures > 0) {
        std::fprintf(stderr, "parakeet_sp_parity: %d failure(s)\n", g_failures);
        return EXIT_FAILURE;
    }
    std::fprintf(stderr, "parakeet_sp_parity: OK\n");
    return EXIT_SUCCESS;
}
