# /// script
# requires-python = ">=3.11,<3.13"
# dependencies = ["sentencepiece==0.2.1", "tokenizers==0.22.1"]
# ///
"""
Emit expected (text, token_ids) pairs for the SentencePiece encoder parity
test (tests/parakeet_sp_parity.cpp).

Each argument is NAME=PATH, where PATH is a SentencePiece .model or a
Hugging Face tokenizer.json; the output has one k_<NAME>_fixtures[] array
per argument. The test encodes every text with Tokenizer::encode() on the
matching GGUF and compares ids.

Usage:
  uv run scripts/sp-tokenizer-parity-fixture.py \\
      parakeet_v3=<parakeet-tdt-0.6b-v3>/tokenizer.json \\
      nemotron_en=<nemotron-speech-streaming-en-0.6b>/tokenizer.model \\
      nemotron35=<nemotron-3.5-asr-streaming-0.6b>/tokenizer.model \\
      > tests/fixtures/parakeet_sp_parity.inc

Texts avoid the cases where the HF conversion of a NeMo tokenizer differs
from SentencePiece itself (whitespace runs, digits after a space) and
user-defined symbols, which the C++ encoder does not prematch.
"""
import sys

TEXTS = [
    "hello world",
    "Glimpse",
    "Groq",
    "Tauri",
    "Garon Grevers",
    "Cloudflare",
    "Superwhisper",
    "Wispr Flow",
    "PostHog",
    "Nemotron",
    "diarization",
    "transcribe.cpp",
    "ESP32",
    "GGUF",
    "Qwen",
    "Mr. O'Neil's co-op",
    "C++ and C#",
    "D\u00e9j\u00e0 vu",
    "na\u00efve caf\u00e9",
    "Gr\u00f6\u00dfe",
    "\u0141\u00f3d\u017a",
    "El equipo de Supabase respondi\u00f3 r\u00e1pido.",
    "Le serveur Cloudflare est tomb\u00e9.",
    "Ich habe Groq in Berlin getestet.",
    "hello\tworld",
    "\u65e5\u672c\u8a9e",
    "emoji \U0001f600 here",
]


def c_escape(s: str) -> str:
    out = []
    for ch in s.encode("utf-8"):
        if ch == 0x22:
            out.append('\\"')
        elif ch == 0x5C:
            out.append("\\\\")
        elif ch == 0x09:
            out.append("\\t")
        elif 0x20 <= ch < 0x7F:
            out.append(chr(ch))
        else:
            out.append(f'\\x{ch:02x}" "')
    return "".join(out)


def encoder(path: str):
    if path.endswith(".json"):
        from tokenizers import Tokenizer

        tok = Tokenizer.from_file(path)
        return lambda s: tok.encode(s, add_special_tokens=False).ids
    import sentencepiece as spm

    sp = spm.SentencePieceProcessor(model_file=path)
    return sp.encode


def main() -> int:
    if len(sys.argv) < 2 or any("=" not in a for a in sys.argv[1:]):
        print(__doc__, file=sys.stderr)
        return 2
    print("// Auto-generated by scripts/sp-tokenizer-parity-fixture.py; regenerate")
    print("// with the command in that script's docstring.")
    print()
    for arg in sys.argv[1:]:
        name, path = arg.split("=", 1)
        enc = encoder(path)
        print(f"constexpr Fixture k_{name}_fixtures[] = {{")
        for text in TEXTS:
            ids = enc(text)
            assert len(ids) <= 32, text
            print(f'    {{ "{c_escape(text)}", {{ {", ".join(str(i) for i in ids)} }}, {len(ids)} }},')
        print("};")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
